name: Build Executable And Publish
env:
  artifact_name: vup_monitors
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  release:
   types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Set up QEMU # for building linux arm64
      uses: docker/setup-qemu-action@v1
    - name: install dependencies
      run: npm install
    - name: change version of package json
      uses: jaywcjlove/github-action-package@main
      with:
        version: ${{ github.ref_name }}
    - name: building executable
      run: |
        npm install pkg -g
        pkg .
    - name: zip the directory
      run: |
        zip -r ${{ env.artifact_name }}.zip ./dist
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
    - name: Upload Release
      id: upload-release-zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./${{ env.artifact_name }}.zip
        asset_name: ${{ env.artifact_name }}.zip
        asset_content_type: application/zip
    
