name: Test Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: |
          npm install
          npm install -g mocha
      - name: test the program
        run: npm run test
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install
      - name: building executable
        run: |
          npm install pkg -g
          pkg .
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: vup_monitors-development
          path: dist
