name: Test Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: |
          npm ci
          npm install -g mocha
      - name: test the program
        run: npm run test